### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by berrywhite96** [OliverHi/home-assistant-xiaomi-fan-card#1]
I installed this beautiful card into my Hassio instance but sadly it does not work at all.
I have no button icons, the buttons also does not work if I try to use them and the states are also not setted correctly.
Didn't had the time to look into it, just getting this error on my dev console:
`xiaomi-fan-card.js:268 Uncaught TypeError: Cannot set properties of undefined (setting 'entity_id')
    at XiaomiFanCard.callService (xiaomi-fan-card.js:268:32)
    at XiaomiFanCard.<anonymous> (xiaomi-fan-card.js:199:42)
    at F.handleEvent (styles.ts:368:1)`

<img width="492" alt="Bildschirmfoto 2022-03-19 um 00 51 52" src="https://user-images.githubusercontent.com/24818127/159097902-d241d100-0a7f-4439-af71-35510689d920.png">

**Comment by Panbug** [comment]
Same here, buttons are invisible but they are there, I can click them, however on/off button isn't working, all other buttons work fine.

**Comment by OliverHi** [comment]
Unfortunately it seems like something has changed on Home Assistant side because the card has also stopped working for me.
I would gladly accept pull requests with updates to fix this. Otherwise I will fix it once I get to but I am not sure when that will be

**Comment by TSA3000** [comment]
> 

Any updates there?

**Comment by OliverHi** [comment]
Not yet, feel free to open a PR though :)
